#!/usr/bin/env python2

#(c) 2016 by Authors
#This file is a part of mosaicFlye program.
#Released under the GPLv2 license (see LICENSE file)

"""
This script sets up environment paths
and runs mosaicFlye without installation.
"""

import os
import sys

root = os.path.dirname(os.path.abspath(__file__))
mosaicRoot = os.path.join(root, "py")
stubRoot = os.path.join(root, "py", "stub")
bin_path = os.path.join(root, "bin")
sys.path.append(root)
sys.path.append(mosaicRoot)
sys.path.append(stubRoot)
sys.path.append(bin_path)
os.environ["PATH"] = bin_path + os.pathsep + os.environ["PATH"]

from disjointig_resolve import mosaic_main
mosaic_main.assemble(sys.argv, bin_path)
